"""Flight Air Map constants."""


ATTRIBUTION = "Flight Air Map Data"

CUSTOM_ATTRIBUTE = 'custom_attribute'

ATTR_FLIGHT_CODE = 'c'.format(CUSTOM_ATTRIBUTE)
ATTR_AIRCRAFT_REGISTRATION = 'reg'.format(CUSTOM_ATTRIBUTE)
ATTR_AIRCRAFT_TYPE = 'ai'.format(CUSTOM_ATTRIBUTE)
ATTR_DEPARTURE_AIRPORT = 'dac'.format(CUSTOM_ATTRIBUTE)
ATTR_ARRIVAL_AIRPORT = 'aac'.format(CUSTOM_ATTRIBUTE)
ATTR_ID = 'fi'.format(CUSTOM_ATTRIBUTE)

